### ISSUE TITLE
Alpine version 3.8 needed in 

### ISSUE THREAD

**Issue by spalfreyman** [tapayne88/marax-monitoring#1]
I was getting the following on build:
ERROR: Service 'marax-adapter' failed to build : The command '/bin/sh -c chmod +x /usr/local/bin/timestamp-line' returned a non-zero code: 139 

I found a similar issue attributed to a newer version of Alpine, if you set FROM alpine:3.8 it seems to work.

**Comment by tapayne88** [comment]
hi @spalfreyman, apologies for the delay! I've tried a few different versions of alpine but I can't seem to replicate the issue. 

Do you know what version of alpine your docker-compose pulled down?

**Comment by spalfreyman** [comment]
no problem, I think its an issue with running it on a Pi Zero & the later versions of alpine (and pretty much everything else) not running correctly on ARMv6 without alteration.  Appologies!
