### ISSUE TITLE
No period in my firmware version

### ISSUE THREAD

**Issue by thom-mac** [tapayne88/marax-monitoring#13]
My Mara X has firmware version 1.23b and there is no period in the version number in the data when I view it in putty. I’m not experienced enough to know what I need to modify or how to modify to make it work. 
![IMG_2944](https://user-images.githubusercontent.com/130811350/232179095-e9b42531-d508-4797-bba8-4438421d9039.jpeg)

**Comment by tapayne88** [comment]
Hi @thom-mac, thanks for raising this!

Ah that's interesting! Yeah, looking at my parsing of the Mara X data I don't account for version strings without periods - good spot!
https://github.com/tapayne88/marax-monitoring/blob/07270cf09610a307da5e9d947b98f9c75fd02ebe/containers/marax-adapter/timestamp-line#L7

I guess if you look in `/var/log/marax/stderr.log` you'll see messages like `Regex failed for line ...`

I'll try find some time to update this to be a bit more flexible!

**Comment by tapayne88** [comment]
Hopefully #14 will have fixed this - it continues to work with my version with is `C1.19` and from my testing it should support yours (and hopefully future versions). Let me know if you're still struggling!

_N.B._ You may need to clean up the old `marax-monitoring_marax-adapter` image before trying to run `sudo docker-compose up`. To remove it you need to run `sudo docker rmi <image_id>` with the image ID - `sudo docker images` should get you that.

Here's how I did it
```
pi@raspberrypi:~ $ sudo docker images
REPOSITORY                       TAG       IMAGE ID       CREATED          SIZE
marax-monitoring_marax-adapter   latest    ebcc4692cb8a   11 minutes ago   8.84MB
telegraf                         1.21      f85dd8aae51c   16 months ago    283MB
influxdb                         1.8       1e79d2a23932   16 months ago    246MB
grafana/grafana                  8.3.3     ffa54d3872e9   16 months ago    241MB
alpine                           3.15      78571b13081b   17 months ago    3.81MB
alpine                           3.12      4b128ebb086e   17 months ago    3.79MB
hello-world                      latest    1ec996c686eb   18 months ago    4.85kB
telegraf                         1.17      e015e9496ef1   19 months ago    231MB
grafana/grafana                  7.5.3     4537c28adef2   2 years ago      169MB
pi@raspberrypi:~ $ sudo docker rmi ebcc4692cb8a
...
```

**Comment by thom-mac** [comment]
Works! Thank you so much. I've been using the heck out of this project and it helped me diagnose an issue I was having with my v1 Mara X. Ended up replacing the gicar to a v2 and it's fixed. I used an old MacBook running pop os but when raspberry pi supplies improve I'll be doing it properly. You can see my posts in the Facebook group Home Espresso Aficionados using graphs from your project. Thanks again!
