### ISSUE TITLE
Baudrate setting?

### ISSUE THREAD

**Issue by a-droo** [tapayne88/marax-monitoring#6]
Hi there - for some reason the marax-adapter is throwing a lot of parse errors and eventually shutting down.
The interface /dev/ttyUSB0 seems to initialize OK.
If I shut down the docker and simply monitor the data streaming from the USB port @ 9600bps, the data coming through looks OK (last few lines in the attached log file). [putty.log](https://github.com/tapayne88/marax-monitoring/files/6641898/putty.log)

Any thoughts of what could be going wrong? Is there a baudrate setting anywhere?

Thanks!

**Comment by tapayne88** [comment]
Hi @a-droo, apologies for the delay!

I'm pretty sure I haven't configured any baud rate so I'm not sure what value it will be using. To be honest my experience in this area is pretty limited.

Have you tried patching the container to use screen?

**Comment by a-droo** [comment]
Hey @tapayne88 thanks for the reply. I had no idea how to go into the environment once running to check out telegram. I ended up building my own setup from scratch using node-red > influxDB > grafana, it was a great learning experience and got it working in a few hours. While your implementation didn't work for me, it did give me the confidence that it could be done. Also got some exposure to docker... need to learn that next so I can containerize my setup. Looking at expanding it with some extra sensors through GPIO in the future!

**Comment by tapayne88** [comment]
@a-droo that's awesome, glad you got a setup that works! I might have a look into swapping out my `cat` command for `screen` as it does feel a little janky. USB and device interfaces are kind of at the limits of my knowledge but hopefully I'll learn something!
